// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhFY7wuxjtiQLgeoCAf4d_-zUAreFZKo',
    appId: '1:348528059658:web:0b2de0ad5e748c7bf4c6f3',
    messagingSenderId: '348528059658',
    projectId: 'lab3mis-e5422',
    authDomain: 'lab3mis-e5422.firebaseapp.com',
    storageBucket: 'lab3mis-e5422.firebasestorage.app',
    measurementId: 'G-FTZDZJ1FD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIIz0X3juxMV10cy9tWWZ5zeSiZ1jRcc',
    appId: '1:348528059658:android:747fce545fbfc1cef4c6f3',
    messagingSenderId: '348528059658',
    projectId: 'lab3mis-e5422',
    storageBucket: 'lab3mis-e5422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZ5pmzU5eK6ZtXmau1jYA_eSFM2wh_3Q',
    appId: '1:348528059658:ios:8af1a6ac2e504691f4c6f3',
    messagingSenderId: '348528059658',
    projectId: 'lab3mis-e5422',
    storageBucket: 'lab3mis-e5422.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZ5pmzU5eK6ZtXmau1jYA_eSFM2wh_3Q',
    appId: '1:348528059658:ios:8af1a6ac2e504691f4c6f3',
    messagingSenderId: '348528059658',
    projectId: 'lab3mis-e5422',
    storageBucket: 'lab3mis-e5422.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPhFY7wuxjtiQLgeoCAf4d_-zUAreFZKo',
    appId: '1:348528059658:web:2bda3f79352cb043f4c6f3',
    messagingSenderId: '348528059658',
    projectId: 'lab3mis-e5422',
    authDomain: 'lab3mis-e5422.firebaseapp.com',
    storageBucket: 'lab3mis-e5422.firebasestorage.app',
    measurementId: 'G-JR3JPG4LVK',
  );
}
